[package]
name = "cynthia_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.107"
colored = "2.0.4"
dotenv = "0.15.0"
handlebars = "4.5.0"
which = "5.0.0"
regex = "1.10.2"
jsonc-parser = { version = "0.23.0", features = ["serde"] }
markdown = "1.0.0-alpha.16"
curl = "0.4.44"
